
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Darwin - 23.6.0 - arm64
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /opt/homebrew/opt/llvm/bin/clang 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is Clang, found in:
        /Users/sonikpav/CLionProjects/bmp-header-viewer-master/cmake-build-debug/CMakeFiles/3.28.1/CompilerIdC/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/Users/sonikpav/CLionProjects/bmp-header-viewer-master/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-uXbPo2"
      binary: "/Users/sonikpav/CLionProjects/bmp-header-viewer-master/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-uXbPo2"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_OSX_ARCHITECTURES: ""
      CMAKE_OSX_DEPLOYMENT_TARGET: ""
      CMAKE_OSX_SYSROOT: "/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/Users/sonikpav/CLionProjects/bmp-header-viewer-master/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-uXbPo2'
        
        Run Build Command(s): /Applications/CLion.app/Contents/bin/ninja/mac/aarch64/ninja -v cmTC_1bd1e
        [1/2] /opt/homebrew/opt/llvm/bin/clang   -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -fcolor-diagnostics   -v -Wl,-v -MD -MT CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o -c /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Homebrew clang version 19.1.3
        Target: arm64-apple-darwin23.6.0
        Thread model: posix
        InstalledDir: /opt/homebrew/Cellar/llvm/19.1.3/bin
        Configuration file: /opt/homebrew/etc/clang/arm64-apple-darwin23.cfg
        System configuration file directory: /opt/homebrew/etc/clang
        User configuration file directory: /Users/sonikpav/.config/clang
        clang: warning: -Wl,-v: 'linker' input unused [-Wunused-command-line-argument]
         (in-process)
         "/opt/homebrew/Cellar/llvm/19.1.3/bin/clang-19" -cc1 -triple arm64-apple-macosx14.0.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -mframe-pointer=non-leaf -ffp-contract=on -fno-rounding-math -funwind-tables=1 -target-sdk-version=14.4 -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -fbuiltin-headers-in-system-modules -fdefine-target-os-macros -target-cpu apple-m1 -target-feature +zcm -target-feature +zcz -target-feature +v8.4a -target-feature +aes -target-feature +altnzcv -target-feature +ccdp -target-feature +complxnum -target-feature +crc -target-feature +dotprod -target-feature +fp-armv8 -target-feature +fp16fml -target-feature +fptoint -target-feature +fullfp16 -target-feature +jsconv -target-feature +lse -target-feature +neon -target-feature +pauth -target-feature +perfmon -target-feature +predres -target-feature +ras -target-feature +rcpc -target-feature +rdm -target-feature +sb -target-feature +sha2 -target-feature +sha3 -target-feature +specrestrict -target-feature +ssbs -target-abi darwinpcs -debugger-tuning=lldb -fdebug-compilation-dir=/Users/sonikpav/CLionProjects/bmp-header-viewer-master/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-uXbPo2 -target-linker-version 1115.7.3 -v -fcoverage-compilation-dir=/Users/sonikpav/CLionProjects/bmp-header-viewer-master/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-uXbPo2 -resource-dir /opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19 -dependency-file CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o.d -MT CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o -sys-header-deps -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/local/include -internal-isystem /opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/include -internal-externc-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include -ferror-limit 19 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fmax-type-align=16 -fcolor-diagnostics -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o -x c /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        clang -cc1 version 19.1.3 based upon LLVM 19.1.3 default target arm64-apple-darwin23.6.0
        ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/local/include"
        ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/Library/Frameworks"
        #include "..." search starts here:
        #include <...> search starts here:
         /opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/include
         /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include
         /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/System/Library/Frameworks (framework directory)
        End of search list.
        [2/2] : && /opt/homebrew/opt/llvm/bin/clang -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -v -Wl,-v CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o -o cmTC_1bd1e   && :
        Homebrew clang version 19.1.3
        Target: arm64-apple-darwin23.6.0
        Thread model: posix
        InstalledDir: /opt/homebrew/Cellar/llvm/19.1.3/bin
        Configuration file: /opt/homebrew/etc/clang/arm64-apple-darwin23.cfg
        System configuration file directory: /opt/homebrew/etc/clang
        User configuration file directory: /Users/sonikpav/.config/clang
         "/usr/bin/ld" -demangle -lto_library /opt/homebrew/Cellar/llvm/19.1.3/lib/libLTO.dylib -dynamic -arch arm64 -platform_version macos 14.0.0 14.4 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -mllvm -enable-linkonceodr-outlining -o cmTC_1bd1e -search_paths_first -headerpad_max_install_names -v CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o -lSystem /opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/lib/darwin/libclang_rt.osx.a
        @(#)PROGRAM:ld PROJECT:ld-1053.12
        BUILD 15:45:29 Feb  3 2024
        configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
        will use ld-classic for: armv6 armv7 armv7s arm64_32 i386 armv6m armv7k armv7m armv7em
        LTO support using: LLVM version 19.1.3 (static support for 29, runtime is 29)
        TAPI support using: Apple TAPI version 15.0.0 (tapi-1500.3.2.2)
        Library search paths:
        	/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/lib
        	/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/lib/swift
        Framework search paths:
        	/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/include]
          add: [/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include]
        end of search list found
        collapse include dir [/opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/include] ==> [/opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/include]
        collapse include dir [/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include] ==> [/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include]
        implicit include dirs: [/opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/include;/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:159 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: '/Users/sonikpav/CLionProjects/bmp-header-viewer-master/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-uXbPo2']
        ignore line: []
        ignore line: [Run Build Command(s): /Applications/CLion.app/Contents/bin/ninja/mac/aarch64/ninja -v cmTC_1bd1e]
        ignore line: [[1/2] /opt/homebrew/opt/llvm/bin/clang   -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -fcolor-diagnostics   -v -Wl -v -MD -MT CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o -c /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeCCompilerABI.c]
        ignore line: [Homebrew clang version 19.1.3]
        ignore line: [Target: arm64-apple-darwin23.6.0]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /opt/homebrew/Cellar/llvm/19.1.3/bin]
        ignore line: [Configuration file: /opt/homebrew/etc/clang/arm64-apple-darwin23.cfg]
        ignore line: [System configuration file directory: /opt/homebrew/etc/clang]
        ignore line: [User configuration file directory: /Users/sonikpav/.config/clang]
        ignore line: [clang: warning: -Wl -v: 'linker' input unused [-Wunused-command-line-argument]]
        ignore line: [ (in-process)]
        ignore line: [ "/opt/homebrew/Cellar/llvm/19.1.3/bin/clang-19" -cc1 -triple arm64-apple-macosx14.0.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -mframe-pointer=non-leaf -ffp-contract=on -fno-rounding-math -funwind-tables=1 -target-sdk-version=14.4 -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -fbuiltin-headers-in-system-modules -fdefine-target-os-macros -target-cpu apple-m1 -target-feature +zcm -target-feature +zcz -target-feature +v8.4a -target-feature +aes -target-feature +altnzcv -target-feature +ccdp -target-feature +complxnum -target-feature +crc -target-feature +dotprod -target-feature +fp-armv8 -target-feature +fp16fml -target-feature +fptoint -target-feature +fullfp16 -target-feature +jsconv -target-feature +lse -target-feature +neon -target-feature +pauth -target-feature +perfmon -target-feature +predres -target-feature +ras -target-feature +rcpc -target-feature +rdm -target-feature +sb -target-feature +sha2 -target-feature +sha3 -target-feature +specrestrict -target-feature +ssbs -target-abi darwinpcs -debugger-tuning=lldb -fdebug-compilation-dir=/Users/sonikpav/CLionProjects/bmp-header-viewer-master/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-uXbPo2 -target-linker-version 1115.7.3 -v -fcoverage-compilation-dir=/Users/sonikpav/CLionProjects/bmp-header-viewer-master/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-uXbPo2 -resource-dir /opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19 -dependency-file CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o.d -MT CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o -sys-header-deps -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/local/include -internal-isystem /opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/include -internal-externc-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include -ferror-limit 19 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fmax-type-align=16 -fcolor-diagnostics -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o -x c /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeCCompilerABI.c]
        ignore line: [clang -cc1 version 19.1.3 based upon LLVM 19.1.3 default target arm64-apple-darwin23.6.0]
        ignore line: [ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/local/include"]
        ignore line: [ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/Library/Frameworks"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/include]
        ignore line: [ /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include]
        ignore line: [ /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/System/Library/Frameworks (framework directory)]
        ignore line: [End of search list.]
        ignore line: [[2/2] : && /opt/homebrew/opt/llvm/bin/clang -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -Wl -search_paths_first -Wl -headerpad_max_install_names -v -Wl -v CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o -o cmTC_1bd1e   && :]
        ignore line: [Homebrew clang version 19.1.3]
        ignore line: [Target: arm64-apple-darwin23.6.0]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /opt/homebrew/Cellar/llvm/19.1.3/bin]
        ignore line: [Configuration file: /opt/homebrew/etc/clang/arm64-apple-darwin23.cfg]
        ignore line: [System configuration file directory: /opt/homebrew/etc/clang]
        ignore line: [User configuration file directory: /Users/sonikpav/.config/clang]
        link line: [ "/usr/bin/ld" -demangle -lto_library /opt/homebrew/Cellar/llvm/19.1.3/lib/libLTO.dylib -dynamic -arch arm64 -platform_version macos 14.0.0 14.4 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -mllvm -enable-linkonceodr-outlining -o cmTC_1bd1e -search_paths_first -headerpad_max_install_names -v CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o -lSystem /opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/lib/darwin/libclang_rt.osx.a]
          arg [/usr/bin/ld] ==> ignore
          arg [-demangle] ==> ignore
          arg [-lto_library] ==> ignore, skip following value
          arg [/opt/homebrew/Cellar/llvm/19.1.3/lib/libLTO.dylib] ==> skip value of -lto_library
          arg [-dynamic] ==> ignore
          arg [-arch] ==> ignore
          arg [arm64] ==> ignore
          arg [-platform_version] ==> ignore
          arg [macos] ==> ignore
          arg [14.0.0] ==> ignore
          arg [14.4] ==> ignore
          arg [-syslibroot] ==> ignore
          arg [/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk] ==> ignore
          arg [-mllvm] ==> ignore
          arg [-enable-linkonceodr-outlining] ==> ignore
          arg [-o] ==> ignore
          arg [cmTC_1bd1e] ==> ignore
          arg [-search_paths_first] ==> ignore
          arg [-headerpad_max_install_names] ==> ignore
          arg [-v] ==> ignore
          arg [CMakeFiles/cmTC_1bd1e.dir/CMakeCCompilerABI.c.o] ==> ignore
          arg [-lSystem] ==> lib [System]
          arg [/opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/lib/darwin/libclang_rt.osx.a] ==> lib [/opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/lib/darwin/libclang_rt.osx.a]
        Library search paths: [;/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/lib;/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/lib/swift]
        Framework search paths: [;/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks]
        remove lib [System]
        remove lib [/opt/homebrew/Cellar/llvm/19.1.3/lib/clang/19/lib/darwin/libclang_rt.osx.a]
        collapse library dir [/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/lib] ==> [/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/lib]
        collapse library dir [/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/lib/swift] ==> [/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/lib/swift]
        collapse framework dir [/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks] ==> [/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks]
        implicit libs: []
        implicit objs: []
        implicit dirs: [/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/lib;/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/lib/swift]
        implicit fwks: [/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks]
      
      
...
