kotlin.code.style=official
version=1.0.0

# WAR
warFileName=server.war

# SCP settings
host=helios.cs.ifmo.ru
port=2222
user=s409295
password=dfhA,0325
destinationDir=web/lab3/wildfly/standalone/deployments
wildflyDir=web/lab3/wildfly
pathToJava=/usr/local

# Alternative Environment
altJavaVersion=17
altJvmArgs=-Dfile.encoding=UTF-8