image: generic-c

stages:
  - check 
  - test

clang_tidy:
  stage: check
  script:
    - echo "Running linter"
    - cat /run-checks.sh
    - /run-checks.sh

test:
  stage: test 
  script:
    - echo "Compiling"
    - make
    - echo "Running test"
    - test/test.sh
